/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.43
 * Generated at: 2017-08-01 10:51:53 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.user;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class mypage_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/C:/meeting/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/meeting/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1496552151886L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.release();
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"//maxcdn.bootstrapcdn.com/bootstrap/latest/css/bootstrap.min.css\">\r\n");
      out.write("   <script src=\"http://code.jquery.com/jquery-1.10.2.js\"></script> \r\n");
      out.write("   <script src=\"//maxcdn.bootstrapcdn.com/bootstrap/latest/js/bootstrap.min.js\"></script>\r\n");
      out.write("  <link href=\"");
      if (_jspx_meth_c_005furl_005f0(_jspx_page_context))
        return;
      out.write("\" rel=\"stylesheet\">\r\n");
      out.write("   <!-- 스프링 시큐리티 ajax csrf설정 403에러  -->\r\n");
      out.write("   <meta name=\"_csrf\" content=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${_csrf.token}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"/>\r\n");
      out.write("   <!-- default header name is X-CSRF-TOKEN -->\r\n");
      out.write("   <meta name=\"_csrf_header\" content=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${_csrf.headerName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"/>\r\n");
      out.write("   <!-- 스프링 시큐리티 ajax csrf설정 403에러  -->\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("\t<style>\r\n");
      out.write("/* \t#profileBox {\r\n");
      out.write("\t\ttext-align: center;\r\n");
      out.write("\t} */\r\n");
      out.write("\t\r\n");
      out.write("\t#profileimage {\r\n");
      out.write("\t\twidth:  200px;\r\n");
      out.write("\t\theight: 200px;\t\t\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tbody {\r\n");
      out.write("\t\tbackground-color: #fafafa;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t#textBox{\r\n");
      out.write("\t\tfont-style: italic;\r\n");
      out.write("\t\tfont-size: large;\r\n");
      out.write("\t\tfont-weight: bold;\r\n");
      out.write("\t\ttext-align: center;\r\n");
      out.write("\t\tpadding: 100px 0px;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.photoLi{\r\n");
      out.write("\t\ttext-align: center;\r\n");
      out.write("\t\twidth: 33%;\r\n");
      out.write("\t\theight: 300px;\r\n");
      out.write("\t\tfloat: left;\r\n");
      out.write("\t}\r\n");
      out.write("\t#photoBox {\r\n");
      out.write("\t\twidth: 100%;\r\n");
      out.write("\t\tlist-style: none;\r\n");
      out.write("\t \tmargin: auto; \r\n");
      out.write("\t}\r\n");
      out.write("\t</style>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write(" \t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/views/header.jsp", out, false);
      out.write(" \r\n");
      out.write("   <br>\r\n");
      out.write("   <br>\r\n");
      out.write("   <br>\r\n");
      out.write("   <br>\r\n");
      out.write("   <div class=\"container\">\r\n");
      out.write("   \t<div class=\"row\" style=\"padding: 50px 80px\">\r\n");
      out.write("   \t\t<div class=\"col-md-6 \">\r\n");
      out.write("   \t\t\t<div id=\"imageBox\" class=\"row\">\r\n");
      out.write("\t   \t\t");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t   \t\t");
      if (_jspx_meth_c_005fif_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t   \t\t</div>\r\n");
      out.write("\t   \t\t <div class=\"row form-group\">\r\n");
      out.write("\t\t\t      <div class=\"col-md-12\">\r\n");
      out.write("\t\t\t         <input type='file' name=\"file\" id=\"file\" >\r\n");
      out.write("\t\t\t         <p class=\"help-block\">보여주고싶은 사진을 올려주세요</p>\r\n");
      out.write("\t\t\t      </div>\r\n");
      out.write("\t\t\t  </div>\r\n");
      out.write("   \t\t</div>\r\n");
      out.write("   \t\t<div id=\"profileBox\"class=\"col-md-6\" style=\"padding: 40px 0px\">\r\n");
      out.write("   \t\t\t<div class=\"row\">\r\n");
      out.write("   \t\t\t\t<div class=\"col-md-6\">\r\n");
      out.write("   \t\t\t\t\t<label>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${userinfo.username}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</label>\r\n");
      out.write("   \t\t\t\t</div>\r\n");
      out.write("   \t\t\t\t<div class=\"col-md-6\">\r\n");
      out.write("   \t\t\t\t\t<button style=\"background: white\">프로필 편집</button>\r\n");
      out.write("   \t\t\t\t</div>\r\n");
      out.write("   \t\t\t</div>\r\n");
      out.write("   \t\t\t<div class=\"row\">\r\n");
      out.write("   \t\t\t\t<div class=\"col-md-3\">\r\n");
      out.write("   \t\t\t\t\t<label>게시물 0개</label>\r\n");
      out.write("   \t\t\t\t</div>\r\n");
      out.write("   \t\t\t\t<div class=\"col-md-3\">\r\n");
      out.write("   \t\t\t\t\t<label>댓글 0개</label>\r\n");
      out.write("   \t\t\t\t</div>\r\n");
      out.write("   \t\t\t\t<div class=\"col-md-6\"></div>\r\n");
      out.write("   \t\t\t</div>\r\n");
      out.write("   \t\t\t<div class=\"row\">\r\n");
      out.write("   \t\t\t\t<div class=\"col-md-3\">\r\n");
      out.write("   \t\t\t\t\t<label>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${userinfo.displayname}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("  </label>\r\n");
      out.write("   \t\t\t\t</div>\r\n");
      out.write("   \t\t\t</div>\r\n");
      out.write("   \t\t</div>\r\n");
      out.write("   \t</div>\r\n");
      out.write("   \t\r\n");
      out.write("   \t<div>\r\n");
      out.write("   \t\t<a href=\"#\" id=\"boardConfirm\">게시물 확인</a>\r\n");
      out.write("   \t\t<a href=\"#\" id=\"replyConfirm\">댓글 게시물 확인</a>\r\n");
      out.write("   \t</div>\r\n");
      out.write("   \t\r\n");
      out.write("   \t<div class=\"row\">\r\n");
      out.write("   \t\t<ul id=\"photoBox\" style=\"width: 100%\"></ul>\r\n");
      out.write("   \t\r\n");
      out.write("   \t</div>\r\n");
      out.write("   \r\n");
      out.write("\t <!--   \t   \r\n");
      out.write("   <div class=\"row\" style=\"background-color: gray\">\r\n");
      out.write("   \t\t<div>\r\n");
      out.write("   \t\t</div>\r\n");
      out.write("   \t\t\t<div>\r\n");
      out.write("   \t\t</div>\r\n");
      out.write("   \t\t\t<div>\r\n");
      out.write("   \t\t</div>\r\n");
      out.write("   </div> -->\r\n");
      out.write("   <br>\r\n");
      out.write("   <br>\r\n");
      out.write("   <br>\r\n");
      out.write("   <br>\r\n");
      out.write("   \t <div class=\"row\" style=\"height: 300px\">\r\n");
      out.write("   \t \t<div class=\"col-md-5\">\r\n");
      out.write("   \t \t\t<img src=\"/resource/imageIcon/insta.jpg\" width=\"100%\" height=\"100%\">\r\n");
      out.write("   \t \t</div>\r\n");
      out.write("   \t \t<div class=\"col-md-7\" style=\"background-color: white\">\r\n");
      out.write("   \t \t\t <div style=\"height: 100%; width: 100%\" id=\"textBox\">\r\n");
      out.write("   \t \t\t \t<p>소중한 순간을 포착하여 공유해보세요.</p>\r\n");
      out.write("   \t \t\t \t<p>앱을 다운로드하고 첫 사진이나 동영상을 공유해보세요.</p>\r\n");
      out.write("   \t \t\t </div>\r\n");
      out.write("   \t \t</div>\r\n");
      out.write("   \t\t<!-- <div class=\"col-md-6 \">\r\n");
      out.write("   \t \t\t<img src=\"/resource/imageIcon/insta.jpg\" width=\"100%\" height=\"100%\">\r\n");
      out.write("   \t \t</div> -->\r\n");
      out.write("  \t </div>\r\n");
      out.write("   </div>\r\n");
      out.write("   <input type=\"hidden\" id=\"username\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${userinfo.username}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("   \r\n");
      out.write("   \t <br>\r\n");
      out.write("   \t <br>\r\n");
      out.write("   \t <br>\r\n");
      out.write("   \t ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/views/footer.jsp", out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("   \r\n");
      out.write("</body>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("$(document).ready(function(){\r\n");
      out.write("/* \tvar uimage= $(\"#profileimage\").val();\r\n");
      out.write("\tconsole.log(uimage) */\r\n");
      out.write("    $(function () {\r\n");
      out.write("       var token = $(\"meta[name='_csrf']\").attr(\"content\");\r\n");
      out.write("       var header = $(\"meta[name='_csrf_header']\").attr(\"content\");\r\n");
      out.write("       $(document).ajaxSend(function(e, xhr, options) {\r\n");
      out.write("          xhr.setRequestHeader(header, token);\r\n");
      out.write("       });\r\n");
      out.write("    });\r\n");
      out.write("\t\r\n");
      out.write("\t  var imageCheck = $(\"#profileimage\").attr(\"alt\"); //현재 이미지경로 \r\n");
      out.write("\t  var username = $(\"#username\").val();\r\n");
      out.write("  \r\n");
      out.write("  /* 이미지 처리 부분  */\r\n");
      out.write("  $(\"#file\").change(function(){\r\n");
      out.write("     console.log(\"sss\");\r\n");
      out.write("     var formData = new FormData();\r\n");
      out.write("      formData.append(\"file\", $(\"input[name=file]\")[0].files[0]);//파일의 정보를 formData에 삽입 \r\n");
      out.write("\r\n");
      out.write("      $.ajax({ //image 파일 폴더에 생성\r\n");
      out.write("          type : \"post\",\r\n");
      out.write("          url : \"/imageUpload?Mypath=my\",\r\n");
      out.write("          dataType : \"text\",\r\n");
      out.write("          data : formData,\r\n");
      out.write("          processData : false,\r\n");
      out.write("          contentType : false,\r\n");
      out.write("          success : function(imgPath) {\r\n");
      out.write("        \t  if(imgPath){\r\n");
      out.write("        \t\t  if(imageCheck === \"default\"){\r\n");
      out.write("            \t\t  $(\"#imageBox\").empty(); //imageBox 안에 태그 비우기 \r\n");
      out.write("                      var str = \"<img src='/displayFile?fileName=\"+imgPath+\"'  id='profileimage' class='img-circle' />\";\r\n");
      out.write("                      $(\"#imageBox\").append(str);\r\n");
      out.write("            \t  }else{\r\n");
      out.write("            \t\t  imageDelete(imageCheck,imgPath);\r\n");
      out.write("            \t  }\r\n");
      out.write("        \t\t  imageDatabseUpload(imgPath);\r\n");
      out.write("        \t  }else{\r\n");
      out.write("        \t\t  alert(\"Image File please\");\r\n");
      out.write("        \t  }\r\n");
      out.write("          }\r\n");
      out.write("      \r\n");
      out.write("       });\r\n");
      out.write("  });\r\n");
      out.write("  \r\n");
      out.write("  //프로필 사진 경로 Db에 저장\r\n");
      out.write("  function imageDatabseUpload(imgPath){\r\n");
      out.write("\t  $.ajax({\r\n");
      out.write("          url : \"/user/myImageDatabaseUpload\",\r\n");
      out.write("          type : \"post\",\r\n");
      out.write("          data : {\r\n");
      out.write("             fileName : imgPath,\r\n");
      out.write("             username : username\r\n");
      out.write("          },\r\n");
      out.write("          dataType : \"text\",\r\n");
      out.write("          success : function(result) {\r\n");
      out.write("        \t  console.log(\"교체성공\");\r\n");
      out.write("          }\r\n");
      out.write("       });\r\n");
      out.write("  }\r\n");
      out.write("  \r\n");
      out.write("  function imageDelete(preUrl,imgPath) { //이미지 삭제 \r\n");
      out.write("      console.log(\"imgPath\"+imgPath);\r\n");
      out.write("      console.log(\"preUrl\"+preUrl);\r\n");
      out.write("         $.ajax({\r\n");
      out.write("            url : \"/deleteFile\",\r\n");
      out.write("            type : \"post\",\r\n");
      out.write("            data : {\r\n");
      out.write("               fileName : preUrl\r\n");
      out.write("            },\r\n");
      out.write("            dataType : \"text\",\r\n");
      out.write("            success : function(result) {\r\n");
      out.write("               $(\"#imageBox\").empty(); //imageBox 안에 태그 비우기 \r\n");
      out.write("                var str = \"<img src='/displayFile?fileName=\"+imgPath+\"' id= 'profileimage' class='img-circle' />\";\r\n");
      out.write("                $(\"#imageBox\").append(str);\r\n");
      out.write("            }\r\n");
      out.write("         });\r\n");
      out.write("     };\r\n");
      out.write("         \r\n");
      out.write("/* 이미지 처리 부분  */\r\n");
      out.write(" \r\n");
      out.write(" \r\n");
      out.write(" //내 게시물 확인 리스트\r\n");
      out.write(" $(\"#boardConfirm\").click(function(event) {\r\n");
      out.write("\t console.log(\"board click\");\r\n");
      out.write("\t $(\"#photoBox\").empty();\r\n");
      out.write("\t $.ajax({\r\n");
      out.write("\t\t    url : \"/user/myBoardConfirm\",\r\n");
      out.write("            type : \"post\",\r\n");
      out.write("            data : {\r\n");
      out.write("               username : username\r\n");
      out.write("            },\r\n");
      out.write("            dataType : \"json\",\r\n");
      out.write("            success : function(result) {\r\n");
      out.write("            \tvar listView=\"\";\r\n");
      out.write("            \tfor(var k in result){\r\n");
      out.write("            \t\tconsole.log(result[k]);\r\n");
      out.write("            \t\tlistView+=\"<li class='photoLi'>\";\r\n");
      out.write("            \t\tlistView+=\t'<a href=\"/board/read?boardno='+result[k].boardno+'\"style=\"width=\"100%\";height=\"100%\"\">';\r\n");
      out.write("            \t\tlistView+= '<img src=\"/displayFile?fileName='+result[k].photo+'\" style=\"border-radius: 5px\" width=\"100%\" height=\"100%\"></a>';\r\n");
      out.write("            \t\tlistView+=\"</li>\";\r\n");
      out.write("            \t}\r\n");
      out.write("            /* \t댓글수 하트수 표시 */\r\n");
      out.write("            /* \tfor(var k in result){\r\n");
      out.write("            \t\ta+=\"<li class='photoLi'>\"\r\n");
      out.write("            \t\ta+=\t'<a href=\"/board/read?boardno='+result[k].boardno+'\" style=\"width=\"100%\";height=\"100%\"\"> <div class=\"listLabelContainer\"><label class=\"listLabel\"><span class=\"glyphicon glyphicon-heart listLabel\" ></span>'+result[k].heartcnt+'개</label>';\r\n");
      out.write("        \t\t\ta+=\t'<label class=\"listLabel\"><span class=\"glyphicon glyphicon-comment listLabel\" ></span> '+result[k].replycnt+' 개</label>';\r\n");
      out.write("            \t\ta+= '</div><img src=\"/displayFile?fileName='+result[k].photo+'\" style=\"border-radius: 5px\" width=\"100%\" height=\"100%\"></a>';\r\n");
      out.write("\t\t\t\t\ta+=\"</li>\";\r\n");
      out.write("            \t} */\r\n");
      out.write("            \t$(\"#photoBox\").append(listView);\r\n");
      out.write("            }\r\n");
      out.write("\t });\r\n");
      out.write("});\r\n");
      out.write("\t\r\n");
      out.write(" //댓글 게시물 확인 리스트\r\n");
      out.write(" $(\"#replyConfirm\").click(function(event) {\r\n");
      out.write("\t console.log(\"reply click\");\r\n");
      out.write("\t $(\"#photoBox\").empty();\r\n");
      out.write("\t $.ajax({\r\n");
      out.write("\t\t    url : \"/user/myReplyConfirm\",\r\n");
      out.write("            type : \"post\",\r\n");
      out.write("            data : {\r\n");
      out.write("               username : username\r\n");
      out.write("            },\r\n");
      out.write("            dataType : \"text\",\r\n");
      out.write("            success : function(result) {\r\n");
      out.write("             \tconsole.log(result);\r\n");
      out.write("            }\r\n");
      out.write("\t  });\r\n");
      out.write(" });\r\n");
      out.write(" \r\n");
      out.write("});\r\n");
      out.write("</script>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005furl_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f0 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f0_reused = false;
    try {
      _jspx_th_c_005furl_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f0.setParent(null);
      // /WEB-INF/views/user/mypage.jsp(9,14) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f0.setValue("/resource/css/main.css");
      int _jspx_eval_c_005furl_005f0 = _jspx_th_c_005furl_005f0.doStartTag();
      if (_jspx_th_c_005furl_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f0);
      _jspx_th_c_005furl_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f0, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f0_reused = false;
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent(null);
      // /WEB-INF/views/user/mypage.jsp(62,6) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${userinfo.profileimage eq null }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t   \t\t \t<img class=\"img-circle\" id=\"profileimage\" src=\"/resource/imageIcon/defaultprofile.png\" alt=\"default\"/> \r\n");
          out.write("\t   \t\t");
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      _jspx_th_c_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f1_reused = false;
    try {
      _jspx_th_c_005fif_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f1.setParent(null);
      // /WEB-INF/views/user/mypage.jsp(65,6) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${userinfo.profileimage ne null }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f1 = _jspx_th_c_005fif_005f1.doStartTag();
      if (_jspx_eval_c_005fif_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t   \t\t \t<img class=\"img-circle\" id=\"profileimage\" src=\"/displayFile?fileName=");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${userinfo.profileimage}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\" alt=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${userinfo.profileimage}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\"  /> \r\n");
          out.write("\t   \t\t\t");
          out.write(" \r\n");
          out.write("\t   \t\t");
          int evalDoAfterBody = _jspx_th_c_005fif_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
      _jspx_th_c_005fif_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f1_reused);
    }
    return false;
  }
}
